import "@/styles/globals.css";
import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import { ReactNode } from "react";

const geistMono = Geist_Mono({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={` ${geistMono.className} dark antialiased`}>
        {children}
      </body>
    </html>
  );
}
